- name: Add key
  hosts: controller
  become: true
  become_user: ansadmin
  tasks:
    - name: Creating inventory file
      copy:
        dest: "/home/ansadmin/inventory"
        content: |
          node1    ansible_user=ansadmin
    - name: Creating ansible.cfg file
      copy:
        dest: "/home/ansadmin/ansible.cfg"
        content: |
          [defaults]
          inventory      = inventory
          host_key_checking = False
