---
- name: Add Node config
  hosts: node1
  become: yes
  tasks:
    - name: Add host to localdns
      lineinfile:
        path: /etc/hosts
        line: 192.168.56.41  node1
    - name: Add controller to localdns
      lineinfile:
        path: /etc/hosts
        line: 192.168.56.40  controller
    - name: make ansadmin with sudo privilages
      lineinfile:
        path: /etc/sudoers
        line: 'ansadmin ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: To set python version 3
      lineinfile:
        path: ~/.bashrc
        line: alias python=python3
    - name: Set python3
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

